#!/usr/bin/env python3
# Autogenerated Aethel wrapper script
import os
import sys

try:
    from aethel.linter import main
except ImportError:
    # Degrade gracefully: a MISSING INSTALL must not hard-fail the commit (a fresh
    # clone or CI without aethel would be blocked for no real violation). Warn and
    # skip (exit 0) unless AETHEL_REQUIRE is set (strict mode, mirrors
    # AETHEL_SKIP_SYNC). Real lint violations still fail below, since main() runs
    # only when the import succeeds.
    hint = (
        "'aethel' is not importable by " + sys.executable + ". "
        "Install it: 'pipx install aethel-cli' (recommended) or 'pip install -e .' in the repo."
    )
    if os.environ.get("AETHEL_REQUIRE"):
        print("Aethel ERROR: " + hint)
        sys.exit(1)
    print(
        "Aethel WARNING (lint skipped): "
        + hint
        + " Set AETHEL_REQUIRE=1 to make a missing install a hard failure."
    )
    sys.exit(0)

if __name__ == "__main__":
    main()
